"""added amount,transaction and friend

Revision ID: 0c1171ae9575
Revises: 07e8580a3a34
Create Date: 2024-08-04 17:23:29.136548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c1171ae9575'
down_revision = '07e8580a3a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settleup')
    op.add_column('transactions', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'notes')
    op.create_table('settleup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('settled_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], name='settleup_payer_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='settleup_receiver_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='settleup_pkey')
    )
    # ### end Alembic commands ###
