"""renamming participant

Revision ID: 7d37ece02c92
Revises: 78ccc83b3da7
Create Date: 2024-07-14 20:33:39.466998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d37ece02c92'
down_revision = '78ccc83b3da7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("splits", column_name="participate_id",new_column_name="participant_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("splits", column_name="participant_id",new_column_name="participate_id")
    
    # ### end Alembic commands ###
