"""added amount

Revision ID: a40ad08c9b9e
Revises: 0c1171ae9575
Create Date: 2024-08-04 17:43:39.176961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40ad08c9b9e'
down_revision = '0c1171ae9575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendships', sa.Column('amount', sa.Numeric(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendships', 'amount')
    # ### end Alembic commands ###
